# Form implementation generated from reading ui file 'D:\OneDrive\workspace\github\learning_item\pyqt6\Qlabel\加载单行文本.py'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


